### ISSUE TITLE
imagetoraster and 16bit images

### ISSUE THREAD

**Issue by jpnp** [OpenPrinting/libcupsfilters#25]
When I print a 16bit TIFF file, imagetoraster fails with this in the debug logs:
```
   DEBUG: TIFF resolution = 70.866142x70.866142, units=3
   DEBUG: Stored resolution = 180x180 PPI
   DEBUG: Bad TIFF dimensions 2104x1488x16x3!
   ERROR: The print file could not be opened.
   ERROR: imagetoraster (PID 259068) stopped with status 1
```
If I convert the tiff to a 16bit PNG (and use a ppd which specifies `/cupsBitsPerColor 16/` then the filter runs and produces a 16bit raster, but it is entirely blank white.

If I force cups to go via imagetopdf by disabling imagetoraster then things are better and gs produces a sensible 16bit raster.  The image values are not exactly the same as the input (some sample's channel values are 1-3 out compared to the original image). i.e. it passes an effectively 14-15bit per channel image to gutenprint.

I'm using Ubuntu 20.04 with cups 2.3.1-9ubuntu1.1 and cups-filters 1.27.4-1, and gutenprint 5.3.4.

**Comment by tillkamppeter** [comment]
Fixed in commits c83bead746 and bb180dcfb0c. Thanks, @Harshit09-lang for your contribution!
