### ISSUE TITLE
HP Envy 4520 Printing issues from Chrome/Chromium

### ISSUE THREAD

**Issue by jmontleon** [OpenPrinting/libcupsfilters#29]
**Describe the bug**
I opened a bug against Chrome due to printing problems that started in version 112.
https://bugs.chromium.org/p/chromium/issues/detail?id=1448735

I did a bisect and tracked down the commit that started causing the issue. After looking at the change, if IIUC they're now printing with a 96 dpi resolution, at least when I use the driverless PPD with this printer.

I've since been able to reproduce the issue by running `lp -o media=letter -o resolution=96dpi onepage-letter.pdf`. If I do `lp -o media=letter -o resolution=300dpi onepage-letter.pdf` the job prints fine. 

My question is mainly whether printing at 96dpi should be valid, and if so is then is this a driver (or printer) bug.

**To Reproduce**
1. Set up an HP Envy 4520 using the driverless PPD
2. `lp -o media=letter -o resolution=96dpi onepage-letter.pdf` or print from Google Chrome 112 or later.

The print job is rendered incorrectly when printed.

**Expected behavior**
A print job without extra artifacts.

**Scans of bad print examples**
![image](https://github.com/OpenPrinting/cups-filters/assets/1850500/0197ffd7-5c65-400a-91f7-67074f6e7d07)
![image](https://github.com/OpenPrinting/cups-filters/assets/1850500/3801e4aa-64fa-4432-8f3f-98f2943e5956)
![image](https://github.com/OpenPrinting/cups-filters/assets/1850500/94653160-71f8-4343-b4b6-27106fa73588)

**System Information:**
 - OS: Fedora 38 (reproduced on 37 as well)
 - Browser: Chrome 112+
 - CUPS 2.4.2, driverless PPD 2.0rc1

**Additional context**
For what it's worth, doing `lp -o media=letter -o resolution=96dpi onepage-letter.pdf` with the hpcups driver works fine.

**Comment by tillkamppeter** [comment]
Now you should be able to print at least as I have now added protection against such bad settings.

But Chromium setting `resolution=96dpi` shows that they do not know what the resolution attribute is for. Looks like they want to tell the user's screen resolution to the printing system. This is not what the attribute is good for, actually, the printing system does not need to know the user's screen resolution.

The resolution attribute is to select one of the printer's (or the driver's) resolution to opt for more quality or more speed. You should also report a bug to the Chromium developers.

Therefore the iPP name is `printer-resolution`, to make it more clear ...

**Comment by tillkamppeter** [comment]
Yes, if you get the GIT master of now or you apply the patch to a recent libcupsfilters (like 2.0rc1) and compile the code you should get a fixed libcupsfilters. The fix makes the `resolution=96dpi` simply ignored, as your printer is not able to print with a resolution of 96 dpi. It does only 300 dpi or 600 dpi. I have tested my fix with your PPD and I get correct raster files in 300 dpi or 600 dpi, which your printer should print correctly. The PDF file from Chromium is correct and one can print it on any printer in the printer's native resolution.

**Comment by jmontleon** [comment]
I got it to work today. Thank you. I ended up patching both this and the prior commit in, which basically brought it up to the master branch and it worked fine. Not sure if the prior commit was also required, or I was just tired and screwing up yesterday, but either way thank you again.
