### ISSUE TITLE
Unreleased Ghostscript 10.01.0 as dependency

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/libcupsfilters#5]
Hi,

I'm checking the new projects to package them in Fedora and see the following requirement in README.md:

```
Ghostscript 10.00.0 is required (10.01.0 is highly recommended)
```

however if I check the [download](https://ghostscript.com/releases/index.html) page of Ghostscript project, I see only version 10.00.0. Is version 10.01.0 available somewhere else?

**Comment by tillkamppeter** [comment]
10.01.0 is the next to come, more or less 6 months after 10.00.0. I recommend it as after 10.00.0 I did some small change  on the CUPS Raster outout device (`cups/gdevcups.c`) and it will be included in 10.01.0.

It is this change in Ghostscript. You can add it as distro patch to 10.00.0 for the time being until you switch to 10.01.0.
```
commit 387f09416ca7364d09415d47df01864b04cbdbc0
Author: Till Kamppeter <till.kamppeter@gmail.com>
Date:   Sun Sep 25 10:02:28 2022 +0200

    CUPS/PWG/Apple Raster output device: Do not match custom size against PPD
    
    If for a job a custom page size is selected, indicated by something
    like "-scupsPageSizeName=Custom.4x8in" or "-scupsPageSizeName=Custom",
    do not try to match the requested page size, given by standard
    Ghostscript parameters like
    "-dDEVICEWIDTHPOINTS=... -dDEVICEHEIGHTPOINTS=...", with the supported
    page sizes defined in the PPD file.
    
    This avoids unwished rotations as reported in
    
        https://github.com/OpenPrinting/cups-filters/issues/484
    
    and also unwished size mismatches if the custom size is very close to
    a size defined in the PPD file.
```
