### ISSUE TITLE
Switch from `cups-config` to `pkg-config`

### ISSUE THREAD

**Issue by Pandapip1** [OpenPrinting/libcupsfilters#55]
`libcupsfilters` uses `cups-config` to find CUPS. It should use `pkg-config` instead.

**Comment by tillkamppeter** [comment]
`pkg-config` is used for finding CUPS 3.x (libcups3), `cups-config`, used for CUPS 2.x will still work with future CUPS 2.x versions (2.5.x).

**Comment by tillkamppeter** [comment]
Please re-open if you need CUPS detection by `pkg-config` for your use case.
