### ISSUE TITLE
Please make release 2.0b3 with LICENSE text

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/libcupsfilters#8]
Hi Till,

I saw the LICENSE text of Apache software license 2.0 is not part of 2.0b2, I saw Makefile.am was fixed later - would you mind releasing 2.0b3 which will have the text?

There is a package review during getting new packages into Fedora and license is one step.

**Comment by tillkamppeter** [comment]
[Done](https://openprinting.github.io/cups-filters-Second-Generation-Third-Beta-Release/)!
